### ISSUE TITLE
sage 9.7: %sh broken

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6193]
running this in a block in a sagews with sage version 9.7 fails with `AttributeError: module 'sage.interfaces.cleaner' has no attribute 'cleaner'`

```
%sh
date
```

I believe this is caused by https://github.com/sagemath/sage/commit/ec1a3cf0f05b38e8de9fdd8fd906e1b950a7d0b2

relevant code to fix is here: 
https://github.com/sagemathinc/cocalc/blob/master/src/smc_sagews/smc_sagews/sage_jupyter.py#L122

(and beware, there might be other API changes as well … and this should be a backwards compatible fix for <=9.6)

**Comment by williamstein** [comment]
They are getting rid of the Sage cleaner since they don't understand why it was necessary.  That's fine.  I was just getting a lot of complaints from users and had just watched "Pulp Fiction" (hence the name "The Cleaner"), so decided to solve these complaints once and for all.

For CoCalc projects (at least) /tmp is a ramdisk that is reset whenever the project restarts.  So it's a very safe place for any of these tmp files to go without any need for a cleaner.

Thanks for finding this; I'm sure it also breaks cocalc-docker.

**Comment by williamstein** [comment]
This broke %x for every single mode x, not just %sh.  That made it a much more severe bug than I had realized.
